export const experienceConstants = {
  GET_EXPERIENCE_REQUEST: 'EXPERIENCE_GET_REQUEST',
  GET_EXPERIENCE_SUCCESS: 'EXPERIENCE_GET_SUCCESS',
  GET_EXPERIENCE_FAILURE: 'EXPERIENCE_GET_FAILURE',

  UPDATE_EXPERIENCE_REQUEST: 'EXPERIENCE_UPDATE_REQUEST',
  UPDATE_EXPERIENCE_SUCCESS: 'EXPERIENCE_UPDATE_SUCCESS',
  UPDATE_EXPERIENCE_FAILURE: 'EXPERIENCE_UPDATE_FAILURE',
};
