export const userConstants = {
  GET_CURRENT_USER_REQUEST: 'CURRENT_USER_GET_REQUEST',
  GET_CURRENT_USER_SUCCESS: 'CURRENT_USER_GET_SUCCESS',
  GET_CURRENT_USER_FAILURE: 'CURRENT_USER_GET_FAILURE',
};
